name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
   # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish Bzor_simple.csproj 
      
     # changes the base-tag in index.html from '/' to 'Bzor_simple' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to Bzor_simple
      run: sed -i 's/<base href="\/" \/>/<base href="\/Bzor_simple\/" \/>/g' index.html
      
     - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
    
